#=============================================================================
# basic.toml --- basic configuration example for SpaceVim
# Copyright (c) 2016-2022 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg@outlook.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = false
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "nil"
    statusline_iseparator = "bar"
    buffer_index_type = 4
    windows_index_type = 3
    enable_tabline_filetype_icon = false
    enable_statusline_mode = false
    statusline_unicode = false
    # Enable vim compatible mode, avoid changing origin vim key bindings
    vimcompatible = false 
    bootstrap_after = 'myspacevim#after'
    bootstrap_before = 'myspacevim#before'

# Enable autocomplete layer
# [[layers]]
  # name = "autocomplete"
  # autocomplete_method = "deoplete"
  # auto_completion_return_key_behavior = "smart"
  # auto_completion_tab_key_behavior = "cycle"
#
# [[layers]]
  # name = 'shell'
  # default_position = 'top'
  # default_height = 30
#
#[[layers]]
 # name = 'lsp'
 # enabled_clients = ['pylsp']
#
# [[layers]]
 # name = "lang#python"
 # python_file_head = [
    # '#!/usr/bin/env python',
    # '# -*- coding: utf-8 -*-',
    # '',
    # ''
 # ]

#[[layers]]
#  name = "lang#rust"
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "cycle"

[[layers]]
name = 'shell'
default_position = 'bottom'
default_height = 30

[[layers]]
  name = "lang#python"

[[layers]]
  name = "lang#javascript"

[[layers]]
  name = "lang#html"
  emmet_leader_key = "<C-e>"
  emmet_filetyps = ['html']

[[layers]]
    name = "unite"
[[layers]]
  name = "git"
